export const ADD_CITY = 'ADD_CITY';
export const DELETE_CITY = 'DELETE_CITY';
export const UPDATE_CITY = 'UPDATE_CITY';

export const FETCHING_WEATHER_DETAILS = 'FETCHING_WEATHER_DETAILS';
export const FETCH_WEATHER_DETAILS_FAILED = 'FETCH_WEATHER_DETAILS_FAILED';
export const FETCH_WEATHER_DETAILS_SUCCEEDED = 'FETCH_WEATHER_DETAILS_SUCCEEDED';

export const FETCHING_LOCATION_DETAILS = 'FETCHING_LOCATION_DETAILS';
export const FETCH_LOCATION_FAILED = 'FETCH_LOCATION_FAILED';
export const FETCH_LOCATION_SUCCEEDED = 'FETCH_LOCATION_SUCCEEDED';