export const ADD_CITY = 'ADD_CITY';
export const DELETE_CITY = 'DELETE_CITY';
export const FETCHING_WEATHER_DETAILS = 'FETCHING_WEATHER_DETAILS';
export const FETCH_WEATHER_DETAILS_FAILED = 'FETCH_WEATHER_DETAILS_FAILED';
export const FETCH_WEATHER_DETAILS_SUCCEEDED = 'FETCH_WEATHER_DETAILS_SUCCEEDED';